-- Curated STARTER SET only; mappings are review prompts, not certifications.
CREATE TABLE "compliance_frameworks" (
 "id" UUID NOT NULL, "key" TEXT NOT NULL, "name" TEXT NOT NULL, "version" TEXT NOT NULL,
 CONSTRAINT "compliance_frameworks_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "compliance_frameworks_key_key" ON "compliance_frameworks"("key");
CREATE TABLE "framework_requirements" (
 "id" UUID NOT NULL, "framework_id" UUID NOT NULL, "ref_code" TEXT NOT NULL,
 "title" TEXT NOT NULL, "description" TEXT NOT NULL,
 CONSTRAINT "framework_requirements_pkey" PRIMARY KEY ("id"),
 CONSTRAINT "framework_requirements_framework_id_fkey" FOREIGN KEY ("framework_id") REFERENCES "compliance_frameworks"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "framework_requirements_framework_id_ref_code_key" ON "framework_requirements"("framework_id", "ref_code");
CREATE TABLE "record_requirements" (
 "id" UUID NOT NULL, "record_id" UUID NOT NULL, "requirement_id" UUID NOT NULL,
 "mapped_by_id" UUID NOT NULL, "mapped_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "auto_mapped" BOOLEAN NOT NULL DEFAULT false,
 CONSTRAINT "record_requirements_pkey" PRIMARY KEY ("id"),
 CONSTRAINT "record_requirements_record_id_fkey" FOREIGN KEY ("record_id") REFERENCES "records"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT "record_requirements_requirement_id_fkey" FOREIGN KEY ("requirement_id") REFERENCES "framework_requirements"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT "record_requirements_mapped_by_id_fkey" FOREIGN KEY ("mapped_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "record_requirements_record_id_requirement_id_key" ON "record_requirements"("record_id", "requirement_id");

INSERT INTO "compliance_frameworks" ("id","key","name","version") VALUES ('4edd53ca-819b-598e-9787-6442a64472ed','NIST_AI_RMF','NIST AI RMF — starter set','1.0 (2023)') ON CONFLICT ("key") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT '7cba1915-8155-5865-84d8-0f80e1cf6055', "id", 'GOVERN 1.1', 'AI-use governance', 'Document applicable policies and legal requirements for this AI use.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT 'a9468453-baa7-5055-a573-8380bb14c2eb', "id", 'GOVERN 1.2', 'Trustworthy AI considerations', 'Consider trustworthy AI characteristics in organizational policies and decisions.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT 'b3d79b8b-ef7e-58a9-904f-558c6a1504ba', "id", 'GOVERN 1.4', 'Transparent risk process', 'Document the risk management process and its outcomes.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT '724f98c6-0036-58ae-b8f2-2cf215a0acba', "id", 'GOVERN 2.1', 'Accountable roles', 'Identify accountable users and reviewers for AI reliance decisions.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT 'cb626196-1561-5b3b-826f-3d55b4dc6636', "id", 'MAP 1.1', 'Use context', 'Document intended purpose, context, stakeholders, and impacts of AI use.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT 'e81d610a-54cb-5aa8-83b4-7a7d680d3864', "id", 'MAP 1.5', 'Risk tolerance', 'Determine organizational risk tolerance for consequential AI use.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT '1922a4f5-90be-5029-ad81-3fdd39395557', "id", 'MAP 2.3', 'Data and output validity', 'Consider scientific integrity, validity, limitations, and data suitability for the use context; do not treat fluent output as verified evidence.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT 'a697b963-47d8-59f5-b141-5e94dc3793e9', "id", 'MAP 5.1', 'Impact likelihood and magnitude', 'Consider likelihood and magnitude of beneficial and harmful impacts on affected parties.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT 'ec4fc640-a854-5392-9bb0-96134b9cb5d9', "id", 'MEASURE 2.5', 'Validity and reliability', 'Evaluate validity and reliability of AI output before relying on it.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT '47938d83-24e7-5e22-a126-4a2a80b3f028', "id", 'MEASURE 2.10', 'Privacy risk', 'Evaluate privacy risks arising from AI use and sensitive inputs.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT '6b26c88f-21f4-526d-9ec0-bc3dd6e62203', "id", 'MANAGE 1.1', 'Proceed decision', 'Determine whether AI use achieves its intended purpose and whether to proceed.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT 'b395205d-40ba-56dc-bf40-4d60776701e1', "id", 'MANAGE 1.3', 'High-priority risk response', 'Develop responses for high-priority risks before consequential reliance.' FROM "compliance_frameworks" WHERE "key"='NIST_AI_RMF' ON CONFLICT ("framework_id","ref_code") DO NOTHING;

INSERT INTO "compliance_frameworks" ("id","key","name","version") VALUES ('c0fd7147-eea7-5dde-b1b1-dbbc27f96a75','EU_AI_ACT','EU AI Act — starter set','Regulation (EU) 2024/1689') ON CONFLICT ("key") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT '4f2b4321-9bca-5e2e-a3c6-5ce63b7cce8d', "id", 'Art. 50(1)', 'Human interaction transparency', 'Applicability check: providers of systems interacting directly with people must inform them they are interacting with AI unless obvious in context; role and exceptions matter.' FROM "compliance_frameworks" WHERE "key"='EU_AI_ACT' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT '7606a2e8-18d2-5656-93c6-1921cc9842bc', "id", 'Art. 50(4)', 'Generated content disclosure', 'Applicability check: deployers must disclose deepfakes and AI-generated/manipulated text published to inform the public on matters of public interest, subject to stated exceptions including human review/editorial responsibility for text. Not every client message or external report is in scope.' FROM "compliance_frameworks" WHERE "key"='EU_AI_ACT' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT 'c63c33d3-cfa1-50b1-b54f-85f03b7577c2', "id", 'Art. 50(5)', 'Clear timely disclosure', 'Where Article 50 disclosures apply, provide clear and distinguishable information no later than first interaction/exposure; consider accessibility.' FROM "compliance_frameworks" WHERE "key"='EU_AI_ACT' ON CONFLICT ("framework_id","ref_code") DO NOTHING;

INSERT INTO "compliance_frameworks" ("id","key","name","version") VALUES ('5732feb5-04a4-558f-a346-220d9ac07541','ISO_42001','ISO/IEC 42001 — starter set','2023') ON CONFLICT ("key") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT 'f0bbeb5e-ab4b-55bc-b99a-3b388c6ca08f', "id", 'A.7.3', 'Acquisition of data', 'Review how data used with AI is acquired and document provenance/authorization as appropriate. Paraphrased Annex A control prompt; not normative standard text.' FROM "compliance_frameworks" WHERE "key"='ISO_42001' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT 'fc160f0f-3627-5594-ad44-b96b9f47bf71', "id", 'A.7.4', 'Quality of data for AI systems', 'Review data quality and fitness for the intended AI use. Paraphrased Annex A control prompt; assess applicability in the organization''s management system.' FROM "compliance_frameworks" WHERE "key"='ISO_42001' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
INSERT INTO "framework_requirements" ("id","framework_id","ref_code","title","description") SELECT '04fe37bb-efc2-53e1-b25c-7fcbd68f1610', "id", 'A.7.5', 'Data provenance', 'Document provenance of relevant input data and evidence. Paraphrased Annex A control prompt; licensed standard remains authoritative.' FROM "compliance_frameworks" WHERE "key"='ISO_42001' ON CONFLICT ("framework_id","ref_code") DO NOTHING;
